#Standard generics
setGeneric("alignPeaks",function(x, strand, npeaks=1000, bandwidth=150, mc.cores=1) standardGeneric("alignPeaks"))
setGeneric("countHitsWindow", function(x, chrLength, windowSize=10^4-1) standardGeneric("countHitsWindow"))
setGeneric("countRepeats", function(reads, mc.cores=1) standardGeneric("countRepeats"))
setGeneric("cmds", function(x, k=2, logscale=TRUE, mc.cores=1, cor.method='pearson') standardGeneric("cmds"))
setGeneric("cmdsFit", function(d, k=2, type='classic', add=FALSE, cor.method='pearson') standardGeneric("cmdsFit"))
setGeneric("ssdCoverage", function(x, mc.cores=1) standardGeneric("ssdCoverage"))
setGeneric("giniCoverage", function(sample, mc.cores=1, mk.plot=FALSE, seqName='missing', species="missing", chrLengths='missing', numSim="missing") standardGeneric("giniCoverage"))
setGeneric("enrichedChrRegions", function(hits1, hits2, chrLength, windowSize=10^4-1, fdr=0.05, nSims=10, mc.cores=1) standardGeneric("enrichedChrRegions"))
setGeneric("enrichedPeaks", function(regions, sample1, sample2, minHeight=100, space, mc.cores=1) standardGeneric("enrichedPeaks"))
setGeneric("enrichedRegions", function(sample1, sample2, regions, minReads=10, mappedreads, pvalFilter=0.05, exact=FALSE, p.adjust.method='none', twoTailed=FALSE, mc.cores=1) standardGeneric("enrichedRegions"))
setGeneric("extendRanges",function(x,seqLen=200,chrlength,mc.cores=1) standardGeneric("extendRanges"))
setGeneric("filterDuplReads",function(x,maxRepeats,fdrOverAmp=.01,negBinomUse=.999,components=0,mc.cores=1) standardGeneric("filterDuplReads"))
setGeneric("islandCounts", function(x, minReads=10, mc.cores=1) standardGeneric("islandCounts"))
setGeneric("mergeRegions",function(intervals,chromosome,score,annot,aggregateFUN='median',maxDist=300) standardGeneric("mergeRegions"))
setGeneric("PeakLocation", function(x, peakDistance=1000, startpos='start_position', endpos='end_position', strand='strand', distance, main='', xlab='Distance (bp)', densityType='kernel',breaks, ...) standardGeneric("PeakLocation"))
setGeneric("regionsCoverage", function(chr, start, end, cover) standardGeneric("regionsCoverage"))
setGeneric("stdPeakLocation", function(x, startpos='start_position', endpos='end_position', strand='strand', distance, main='', xlab='Distance relative to feature length', xaxt='n', xlim=c(-1,2), densityType='kernel', nbreaks=10, ...) standardGeneric("stdPeakLocation"))
setGeneric("tabDuplReads", function(x, minRepeats=1, mc.cores=1) standardGeneric("tabDuplReads"))
setGeneric("listOverlap", function(list1, list2, list3, univ, ...) standardGeneric("listOverlap"))
